server:
  port: 8080

spring:
  application:
    name: foodtrack

  session:
    store-type: none # Disable Spring Session — prevents conflict with Remember Me cookies

  datasource:
    url: jdbc:mysql://localhost:3306/sipangan_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
    username: root
    password: tarikolot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

logging:
  level:
    com.foodtrack: DEBUG
    org.springframework.security: WARN

gemini:
  api:
    key: "<ISI DENGAN API GEMINI>"
